### ISSUE TITLE
Implement DB(for iteration 1)Implement relationship diagram so as to understand concepts between tables

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#24]

**Comment by yishioka** [comment]
I updated task name.

**Comment by manighotra** [comment]
- Task completed
- Followed up with everyone in the team regarding this
- Database backed up and sent to everyone to go ahead with the development and designing

**Comment by yishioka** [comment]
I got information from Mandeep.

Completed date: Feb 27th
Actual time: 2.0 hours
