### ISSUE TITLE
Implement registration form including page validation

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#26]
#5

**Comment by maunilshah** [comment]
Finished the task in 2.10 hours. Took 0.40 hours extra because I had gone for lunch. Started the task at 11:53 AM and Closed this task at 2:03 PM on 03/01/2015.

**Comment by yishioka** [comment]
You forgot to remove "Suspended" label after lunch.
You took 40 minutes extra; however, that was lunch time, so, you finished this task on time.

**Comment by maunilshah** [comment]
Oh sorry for that but I did remove it. I am out right now for work, but
will check it when I am home. And I also had a question. I have been
assigned a task named code and integrate members page. But if I recollect
then professor had said that no coding for the 1st iteration. What he wants
is the designing. So I was a bit confused about that task. Could you please
elaborate it?

**Comment by yishioka** [comment]
> professor had said that no coding for the 1st iteration.

Actually, I missed that part. but yesterday other developers also said the same thing.
Sorry, I am also confused, if we only focus on designing for 1st iteration,
we cannot close any implementation tasks because "Closed" means, 100% completed that task.
However, 2nd iteration starts about 8 hours later. This iteration we can implement anything.
Let's discuss this at tomorrow's meeting, which tasks are completed 100%, which are not.
if we need to implement after "closed", I need to re-open that task.
I'll attend the meeting after 4:30pm, I have a Comp321 class 2:30pm to 4:30pm.
