### ISSUE TITLE
Return registration confirmation message

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#28]
#5

**Comment by yishioka** [comment]
Can you upload your files?

**Comment by bytesandbites** [comment]
sure i will upload whatever i have so far because i was working at my
friends place on her computer, and i no access togithub nor visual studio
as it is pretty late and i have to go home

**Comment by yishioka** [comment]
At that time, she had a problem, she doesn't have her laptop.
March 3rd, she got her laptop and she can work well.

----- Neha's email-----------2015/3/1 22:42:20------------
sure i will upload whatever i have so far because i was working at my
friends place on her computer, and i no access togithub nor visual studio
as it is pretty late and i have to go home
----- Neha's email-----------
