### ISSUE TITLE
Framework(programming)

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#33]
#2

**Comment by yanweidtc** [comment]
resolve the conflict between visual studio and github 
teach everyone how to use our framework and how to use github
8 hours

**Comment by yanweidtc** [comment]
Design the Default page for some to revise 1.5hours

**Comment by yishioka** [comment]
This means, you completed this task in total 9.5 hours.
Completed date : Feb 26th.

**Comment by yanweidtc** [comment]
0b0906e529fe2e47804ab4207f9f0be66167656f
