### ISSUE TITLE
Code and implement add/delete/edit features for Books

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#38]
#2

**Comment by andyfengc** [comment]
Spent 5 hours because configure the development environment and programming framework and learn  new .Net controls such as Calendar, FileUpload

Manage book:
BookListView.aspx

**Comment by andyfengc** [comment]
Finished date: February 27
Actual Hours: 5
Reasons for More/Less time than Estimated hours: Configure the development environment and programming framework. Learn new .Net controls such as Calendar, FileUpload.

**Comment by andyfengc** [comment]
609b65b6ccb5ded2531252a7652094ad7e018f8d
