### ISSUE TITLE
Create and update SQL statements for Books

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#46]
#2

**Comment by andyfengc** [comment]
Spent 3 hours because contact Mandeep to modify tables

**Comment by andyfengc** [comment]
Finished date: February 27.
Actual Hours: 3
Reasons for More/Less time than Estimated hours: contact Mandeep to modify tables, such as set primary key as auto-incremental, set attachment datatype as varchar, increase datatype length of some fields.

**Comment by andyfengc** [comment]
609b65b6ccb5ded2531252a7652094ad7e018f8d
