### ISSUE TITLE
Visitors can register to become member

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#5]

**Comment by manighotra** [comment]
I think this user story is finished and need to be closed by Scrum master

**Comment by yishioka** [comment]
I tested this user story on March 9th.
I found bugs and sent email to all developers.

I tested again on March 10th, some bugs are fixed,
but I found another bug and sent email to all developers.

**Comment by manighotra** [comment]
@yishioka : i think this user story is tested by you but is not closed yet

**Comment by yishioka** [comment]
I tested that a visitor can become a member,
so I closed this.
