### ISSUE TITLE
Design information management page for eBooks

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#51]
#2

**Comment by yanweidtc** [comment]
edit and update needs helpo

**Comment by yishioka** [comment]
What is the problem? What kind of help do you need?
Please specify this, and if this is technical issue, ask other developers,
if this is about specification, ask the customer(me).

Today, we have a class, can you tell us?

**Comment by yanweidtc** [comment]
1.5hours

**Comment by yanweidtc** [comment]
4dcd9a1009950e1dbf2764c5270dd0208c5e0453
