### ISSUE TITLE
Design information management page for DVDs/CDs/Blu-Rays

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#52]
#2

**Comment by yanweidtc** [comment]
50%

**Comment by yishioka** [comment]
(When you start work, please put "In process" label, I told you yesterday, and you did it.)
If you stop your work in the half way, please use "Suspended" label.
Then, you restart your work, please remove "Suspended" label.
Otherwise, I cannot calculate your time.
If you had a difficulty, also put "Suspended" and leave a comment.

**Comment by yanweidtc** [comment]
3.0hours

**Comment by yanweidtc** [comment]
7d9a8296b51bb7f1e8a19a10fd7dd4032c204b8b
