### ISSUE TITLE
Design information management page for PCs

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#53]
#2

**Comment by yanweidtc** [comment]
processed

**Comment by yishioka** [comment]
please use "In process" label from next time.

**Comment by yanweidtc** [comment]
finished 2hrs

**Comment by yanweidtc** [comment]
02/3/2015 completed
but the maunil upload the conflicts files to the github,
because of this problems i can not submit that on 01/03/2015

**Comment by yanweidtc** [comment]
4dcd9a1009950e1dbf2764c5270dd0208c5e0453
