### ISSUE TITLE
Prepare 10 sample records for eBooks

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#55]
#2

**Comment by yanweidtc** [comment]
finshed

**Comment by yanweidtc** [comment]
1.5hours
02/3/2015 completed
but the maunil upload the conflicts files to the github,
because of this problems i can not submit that on 01/03/2015

**Comment by yanweidtc** [comment]
4dcd9a1009950e1dbf2764c5270dd0208c5e0453
