### ISSUE TITLE
Prepare 10 sample records for PCs

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#57]
#2

**Comment by yanweidtc** [comment]
alsmost finished

**Comment by yanweidtc** [comment]
finished

**Comment by yanweidtc** [comment]
1.5hours
02/3/2015 completed
but the maunil upload the conflicts files to the github,
because of this problems i can not submit that on 01/03/2015

**Comment by manighotra** [comment]
I Created the data and will send all developers the SQL file in 10 minutes after generating the database scripts

**Comment by yanweidtc** [comment]
4dcd9a1009950e1dbf2764c5270dd0208c5e0453
