### ISSUE TITLE
Design members sign in page

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#67]
#3

**Comment by maunilshah** [comment]
Task completed in 2 hours. I took 1 hour extra out of which 0.5 hour was for dinner and another 0.5 hour was for solving an error. I started this task at 11:49 PM and closed this task at 1:49 AM. I submitted this task on 02/02/2015.

**Comment by yishioka** [comment]
Is your pc's time zone UTC-5:00?
When I mouse over "In process", I see "2015-03-02 04:50:01",
Actually, now is 02:50. I think your pc's time zone is UTC+0:00.

Anyway I'll include this task in 1st iteration because you started before March 2nd.
solving error is also part of the task, so actual time this task is 1.5 hour.
