### ISSUE TITLE
code master page

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#79]
#4

**Comment by yishioka** [comment]
When you suspended your work, please put "Suspended" label.
When you close this task, please leave an actual time in comment.

**Comment by bytesandbites** [comment]
sorry due some technical problem I was unable to end this task
I did it now

**Comment by yishioka** [comment]
I am not sure about your comment.
If you completed this task, please leave a comment with actual time and why did you take so long.
please write down about technical problems. If someone had the same problem, this would help.
