### ISSUE TITLE
coding for providing appropriate page based on the type of user

### ISSUE THREAD

**Issue by yishioka** [TeamIshioka/Team_Ishioka#82]
#3

**Comment by yishioka** [comment]
When you suspended your work, please put "Suspended" label.
When you close this task, please leave an actual time in comment.

**Comment by manighotra** [comment]
@yishioka : i think this task is finished but is not closed as we tested the session handling  @hardik12

**Comment by bytesandbites** [comment]
i took hardiks help to complete this task. so i will close it now
